### ISSUE TITLE
"Finally, add tokens to your environment variables named GITLAB_URL and GITHUB_URL which should match the server you want to scan."

### ISSUE THREAD

**Issue by DimitrisPr** [salesforce/DazedAndConfused#7]
Could you please give an example for 

> Finally, add tokens to your environment variables named GITLAB_URL and GITHUB_URL which should match the server you want to scan?

I am not sure what to set the env variable to. 

* Our company is **not** using GitHub enterprise. Will this work with basic repos?

**Comment by jsmithsalesforce** [comment]
GITHUB_URL will be the URL for a private GitHub server.
You can also use the public GitHub.com if you would like.
